### ISSUE TITLE
arbeit aufteilen & git

### ISSUE THREAD

**Issue by CasCodes** [CasCodes/Ticketautomat#1]
# //todo morgen

- [x] eigene branches :palm_tree: 
- [x] UI planen :eye: 
   -  welche features?
   - wer macht was
- [x] basic functions aufteilen & schreiben :man_technologist:

**Comment by CasCodes** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/64489325/151962897-5b7bb52a-6007-4aec-8d3e-b08f9339bd04.png)

**Comment by CasCodes** [comment]
@rubenkol @VinceDerPrince was haltet ihr von einer pop-up nachricht on save pressed? kann man iwie einfach in vaadin einbauen

**Comment by VinceDerPrince** [comment]
> @rubenkol @VinceDerPrince was haltet ihr von einer pop-up nachricht on save pressed? kann man iwie einfach in vaadin einbauen

fände ich gut als feedback, aber mir ist aufgefallen, dass wir den Save button nicht brauchen mit der "OnChange" function.
Für den Buy Button kommt dann ja eh ein neues Fenster nehme ich mal an.

**Comment by CasCodes** [comment]
vincent: variablen fuer die input felder
caspar: price mit user input vergleichen und speichern
