### ISSUE TITLE
stuff to work on

### ISSUE THREAD

**Issue by CasCodes** [CasCodes/Ticketautomat#5]
# TODO

- [x] Email content -> figure out html stuff :man_technologist: 
   - [x] Random Code generator
- [ ] Reset all fields after purchase :dollar: 
   - Maybe add some kind of "email send" pop up in the bottom left?

Any further ideas? :bulb:  Otherwise we would basically be finished with the main part!. :+1:

**Comment by CasCodes** [comment]
I just quickly added the "email send" pop up :cactus:

**Comment by CasCodes** [comment]
- [x] add password to seperate file and gitignore
- [x] try to fix database?

**Comment by CasCodes** [comment]
- [ ] Rick the roll!

**Comment by CasCodes** [comment]
- [ ] Email send failed popup
